package com.smartlogis.deliveryservice.domain.exception;

import org.springframework.http.HttpStatus;

import com.smartlogis.common.exception.MessageCode;

public enum DeliveryMessageCode implements MessageCode {
	// Delivery 관련
	DELIVERY_NOT_FOUND("DELIVERY.NOT_FOUND", HttpStatus.NOT_FOUND),
	DELIVERY_CANCEL_FAILED("DELIVERY.CANCEL_FAILED", HttpStatus.BAD_REQUEST),
	DELIVERY_INVALID_STATUS("DELIVERY.INVALID_STATUS", HttpStatus.BAD_REQUEST),
	DELIVERY_ALREADY_COMPLETED("DELIVERY.ALREADY_COMPLETED", HttpStatus.BAD_REQUEST),
	DELIVERY_ALREADY_CANCELED("DELIVERY.ALREADY_CANCELED", HttpStatus.BAD_REQUEST),

	// DeliveryHistory 관련
	DELIVERY_HISTORY_NOT_FOUND("DELIVERY.HISTORY_NOT_FOUND", HttpStatus.NOT_FOUND),
	DELIVERY_HISTORY_INVALID_STATUS("DELIVERY.HISTORY_INVALID_STATUS", HttpStatus.BAD_REQUEST),
	DELIVERY_HISTORY_INVALID_SEQUENCE("DELIVERY.HISTORY_INVALID_SEQUENCE", HttpStatus.BAD_REQUEST),

	// 상태 전이 관련
	DELIVERY_INVALID_STATUS_TRANSITION("DELIVERY.INVALID_STATUS_TRANSITION", HttpStatus.BAD_REQUEST),
	DELIVERY_HUB_DELIVERY_NOT_AVAILABLE("DELIVERY.HUB_DELIVERY_NOT_AVAILABLE", HttpStatus.BAD_REQUEST),
	DELIVERY_COMPANY_DELIVERY_NOT_AVAILABLE("DELIVERY.COMPANY_DELIVERY_NOT_AVAILABLE", HttpStatus.BAD_REQUEST),
	DELIVERY_COMPLETION_NOT_AVAILABLE("DELIVERY.COMPLETION_NOT_AVAILABLE", HttpStatus.BAD_REQUEST),

	// 배송 담당자 관련
	DELIVERY_MANAGER_NOT_ASSIGNED("DELIVERY.MANAGER_NOT_ASSIGNED", HttpStatus.BAD_REQUEST),
	DELIVERY_MANAGER_ALREADY_ASSIGNED("DELIVERY.MANAGER_ALREADY_ASSIGNED", HttpStatus.BAD_REQUEST),

	// 유효성 검사
	DELIVERY_INVALID_ADDRESS("DELIVERY.INVALID_ADDRESS", HttpStatus.BAD_REQUEST),
	DELIVERY_INVALID_HUB("DELIVERY.INVALID_HUB", HttpStatus.BAD_REQUEST),

	// 외부 서비스 호출 관련
	DELIVERY_ORDER_ITEM_NOT_FOUND("DELIVERY.ORDER_ITEM_NOT_FOUND", HttpStatus.BAD_REQUEST),
	DELIVERY_EXTERNAL_SERVICE_ERROR("DELIVERY.EXTERNAL_SERVICE_ERROR", HttpStatus.SERVICE_UNAVAILABLE);

	private final String code;
	private final HttpStatus status;

	DeliveryMessageCode(String code, HttpStatus status) {
		this.code = code;
		this.status = status;
	}

	@Override
	public String getCode() {
		return code;
	}

	@Override
	public HttpStatus getStatus() {
		return status;
	}
}
